server:
  host: localhost
  port: 8080
  pubsub:
    provider: redis
routes:
  - endpoint: "/api/ws/test"
    topics:
      - "/test/orders"
      - "/test/status"
    plugins:
      middleware:
        - "./examples/docker-compose/plugins/auth.so"
        - "./examples/docker-compose/plugins/awesome-middleware.so"
      message-enrichment:
        - "./examples/docker-compose/plugins/enrich-pizza.so"

  - endpoint: '/api/ws/cool-endpoint/:id/orders'
    topics:
      - "/cool-topic/:id/orders"
    plugins:
      middleware:
        - "./examples/docker-compose/plugins/auth.so"
        - "./examples/docker-compose/plugins/awesome-middleware.so"
      message-enrichment:
        - "./examples/docker-compose/plugins/enrich-pizza.so"
