server:
  port: 8080
routes:
  - endpoint: "/api/ws/test"
    topic: "/test"
    plugins:
      middleware:
        - "./plugins/auth.so"
      message-enrichment:
        - "./plugins/enrich-pizza.so"

  - endpoint: '/api/ws/cool-endpoint/:id/orders'
    topic: "/cool-topic/*/orders"
    plugins:
      middleware:
        - "./plugins/auth.so"
        - "./plugins/awesome-middleware.so"
      message-enrichment:
        - "./plugins/enrich-pizza.so"
