server:
  host: localhost
  port: 8080
  pubsub:
    provider: redis
routes:
  - endpoint: "/api/ws/customers/:customerId/orders/:orderId/updates"
    topics:
      - "/customers/:customerId/orders/:orderId/updates"
    plugins:
      middleware:
        - "./plugins/authenticateCustomerPlugin.so"
      message-enrichment:
        - "./plugins/enrichOrderUpdate.so"

  - endpoint: "/api/ws/customers/:customerId/notifications"
    topics:
      - "/customers/:customerId/notifications"
    plugins:
      middleware:
        - "./plugins/authenticateCustomerPlugin.so"
