server:
  host: localhost
  port: 8080
  pubsub:
    provider: redis
routes:
  - endpoint: "/orders/:id/events"
    topics:
      - "/orders/:id/events"
    plugins:
      middleware:
        - "./plugins/auth.so"
  
  - endpoint: "/api/ws/test"
    topics:
      - "/orders/:id/events"

  - endpoint: "/api/ws/customers/:customerId/notifications"
    topics:
      - "/customers/:customerId/notifications"
    plugins:
      middleware:
        - "./plugins/authenticateCustomerPlugin.so"
