server:
  host: localhost
  port: 8080
  pubsub:
    provider: redis
routes:

  - endpoint: "/delivery/:id/events"
    topics:
      - "/orders/:id/events"

  - endpoint: "/store/:id/events"
    topics:
      - "/orders/:id/events"

  - endpoint: '/api/ws/cool-endpoint/:id/orders'
    topics:
      - "/cool-topic/:id/orders"
    plugins:
      middleware:
        - "./plugins/auth.so"
        - "./plugins/awesome-middleware.so"
      message-enrichment:
        - "./plugins/enrich-pizza.so"
