version: "3.9"

# [BUILD THE EXAMPLE]
# docker compose up

# [STOP RUNNING THE EXAMPLE]
# docker compose down

# [MANUALLY SEND REDIS MESSAGES]
# docker exec -it examples-redis-1 redis-cli

services:
  switchboard:
    image: "jettcrowson/switchboard:0.0.2"
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDRESS: redis:6379
      POSTGRES_ADDRESS: postgres:5431
    volumes:
      - ./config.yaml:/switchboard/config.yaml
      - ./plugins:/switchboard/plugins
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:latest"
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: "switchboard_admin"
      POSTGRES_PASSWORD: "12345687"
      DB_NAME: "go_test"
    volumes:
      - ../loginService/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  auth:
    image: "mtran2021/login-service:0.0.1"
    ports:
      - "8081:8081"
    volumes:
      - ../loginService/.env:/.env
  delivery-service:
    image: "mtran2021/delivery-service:0.1"
    ports:
      - "12345:12345"
    environment:
      REDIS_ADDRESS: redis:6379
  store-service:
    image: "mtran2021/store-service:0.1"
    ports:
      - "54321:54321"
    environment:
      REDIS_ADDRESS: redis:6379
